# Base configs
baseurl: "https://felixzangerl.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Felix Zangerl"
subtitle: "See the world through my eyes!"
author: "Felix Zangerl"
header:
 title: "Photography"
 subtitle: "by Felix Zangerl"
footer:
 name: "Hey there, my name is Felix"
 bio: "..."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/FelixZangerl"
  twitter: "https://twitter.com/FelixZangerl"
  instagram: "https://www.instagram.com/felixzangerl"
  dribbble: ""
  linkedin: ""
  github: "https://github.com/FelixZangerl"
