# Base configs
baseurl: "https://felixzangerl.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Felix Zangerl"
subtitle: "..."
author: "Felix Zangerl"
header:
 title: "Photography"
 subtitle: "by Felix Zangerl"
footer:
 name: "Hey there, my name is Felix"
 bio: "..."
 name: "Felix Zangerl"
 bio: "photographer based in Vienna hit me up via felix.zangerl[at]gmail.com and follow me on Social Media"
 github: ""
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/FelixZangerl"
  twitter: "https://twitter.com/FelixZangerl"
  instagram: "https://www.instagram.com/felixzangerl"
  linkedin: "https://www.linkedin.com/in/felix-zangerl-152003164/"
  github: "https://github.com/FelixZangerl"
